//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasMateria()
        {
            this.PersonaMateria = new HashSet<PersonaMateria>();
        }
    
        public int Id { get; set; }
        public double Notas { get; set; }
        public int Periodo_Id { get; set; }

        public int Materia_id { get; set; }
        public int Estudiante_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<PersonaMateria> PersonaMateria { get; set; }
        public  Periodo Periodoes { get; set; }
    }
}
