//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaMateria
    {
        public int Id { get; set; }
        public int Materia_Id { get; set; }
        public int Persona_Id { get; set; }
        public Nullable<int> Notas_Materias_Id { get; set; }
    
        public  Persona Persona { get; set; }
        public  Materia Materias { get; set; }
        public  NotasMateria NotasMaterias { get; set; }
    }
}
